# Session 17: Working with a Data Frame

By: Viktoria Haghani

Session Date: TBD

Last Updated: 2026-01-30

Reference materials include teaching material from Dr. Nick Ulle.

## Summarizing Data in a Data Frame

In the last session, we started working with the Terns dataset. Initiate a new Jupyter notebook called `02_summarize_data.ipynb`. Load the appropriate modules and data:

### Import Modules

In [1]:
import polars as pl

### Load Data

In [2]:
terns = pl.read_csv("../Session_16/2000-2023_ca_least_tern.csv")

### Summarizing Data Frames

The `.glimpse` method provides a structural summary of a data frame. The method
lists the data frame's shape and column names, as well as the type of data in
each column and a few example values. Try calling `.glimpse` on the `terns`
data frame:

In [3]:
terns.glimpse()

Rows: 791
Columns: 43
$ year                <i64> 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000
$ site_name           <str> 'PITTSBURG POWER PLANT', 'ALBANY CENTRAL AVE', 'ALAMEDA POINT', 'KETTLEMAN CITY', 'OCEANO DUNES STATE VEHICULAR RECREATION AREA', 'RANCHO GUADALUPE DUNES PRESERVE', 'VANDENBERG SFB', 'SANTA CLARA RIVER MCGRATH STATE BEACH', 'ORMOND BEACH', 'NBVC POINT MUGU'
$ site_name_2013_2018 <str> 'Pittsburg Power Plant', 'NA_NO POLYGON', 'Alameda Point', 'Kettleman', 'Oceano Dunes State Vehicular Recreation Area', 'Rancho Guadalupe Dunes Preserve', 'Vandenberg AFB', 'Santa Clara River', 'Ormond Beach', 'NBVC Point Mugu'
$ site_name_1988_2001 <str> 'NA_2013_2018 POLYGON', 'Albany Central Avenue', 'NA_2013_2018 POLYGON', 'NA_2013_2018 POLYGON', 'NA_2013_2018 POLYGON', 'NA_2013_2018 POLYGON', 'NA_2013_2018 POLYGON', 'NA_2013_2018 POLYGON', 'NA_2013_2018 POLYGON', 'NA_2013_2018 POLYGON'
$ site_abbr           <str> 'PITT_POWER', 'AL_CENTAVE', 'ALAM_PT', 'KET_CTY', 'OCEANO_DUNES', 'RGDP', 'VAN_SFB', 'S_CLAR_MCG', 'ORMOND', 'PT_MUGU'
$ region_3            <str> 'S.F._BAY', 'S.F._BAY', 'S.F._BAY', 'KINGS', 'CENTRAL', 'CENTRAL', 'CENTRAL', 'SOUTHERN', 'SOUTHERN', 'SOUTHERN'
$ region_4            <str> 'S.F._BAY', 'S.F._BAY', 'S.F._BAY', 'KINGS', 'CENTRAL', 'CENTRAL', 'CENTRAL', 'VENTURA', 'VENTURA', 'VENTURA'
$ event               <str> 'LA_NINA', 'LA_NINA', 'LA_NINA', 'LA_NINA', 'LA_NINA', 'LA_NINA', 'LA_NINA', 'LA_NINA', 'LA_NINA', 'LA_NINA'
$ bp_min              <f64> 15.0, 6.0, 282.0, 2.0, 4.0, 9.0, 30.0, 21.0, 73.0, 166.0
$ bp_max              <f64> 15.0, 12.0, 301.0, 3.0, 5.0, 9.0, 32.0, 21.0, 73.0, 167.0
$ fl_min              <i64> 16, 1, 200, 1, 4, 17, 11, 9, 60, 64
$ fl_max              <i64> 18, 1, 230, 2, 4, 17, 11, 9, 65, 64
$ total_nests         <i64> 15, 20, 312, 3, 5, 9, 32, 22, 73, 252
$ nonpred_eggs        <i64> 3, None, 124, None, 2, 0, None, 4, 2, None
$ nonpred_chicks      <i64> 0, None, 81, 3, 0, 1, 27, 3, 0, None
$ nonpred_fl          <i64> 0, None, 2, 1, 0, 0, 0, None, 0, None
$ nonpred_ad          <i64> 0, None, 1, 6, 0, 0, 0, None, 0, None
$ pred_control        <str> None, None, None, None, None, None, None, None, None, None
$ pred_eggs           <i64> 4, None, 17, None, 0, None, 0, None, None, None
$ pred_chicks         <i64> 2, None, 0, None, 4, None, 3, None, None, None
$ pred_fl             <i64> 0, None, 0, None, 0, None, 0, None, None, None
$ pred_ad             <i64> 0, None, 0, None, 0, None, 0, None, None, None
$ pred_pefa           <str> 'N', None, 'N', None, 'N', None, 'N', None, 'N', None
$ pred_coy_fox        <str> 'N', None, 'N', None, 'N', None, 'N', None, 'N', None
$ pred_meso           <str> 'N', None, 'N', None, 'N', None, 'N', None, 'Y', None
$ pred_owlspp         <str> 'N', None, 'N', None, 'N', None, 'N', None, 'N', None
$ pred_corvid         <str> 'Y', None, 'N', None, 'N', None, 'N', None, 'N', None
$ pred_other_raptor   <str> 'Y', None, 'Y', None, 'N', None, 'Y', None, 'Y', None
$ pred_other_avian    <str> 'N', None, 'Y', None, 'Y', None, 'N', None, 'N', None
$ pred_misc           <str> 'N', None, 'N', None, 'N', None, 'N', None, 'N', None
$ total_pefa          <i64> 0, None, 0, None, 0, None, 0, None, None, None
$ total_coy_fox       <i64> 0, None, 0, None, 0, None, 0, None, None, None
$ total_meso          <i64> 0, None, 0, None, 0, None, 0, None, None, None
$ total_owlspp        <i64> 0, None, 0, None, 0, None, 0, None, None, None
$ total_corvid        <i64> 4, None, 0, None, 0, None, 0, None, None, None
$ total_other_raptor  <i64> 2, None, 6, None, 0, None, 3, None, None, None
$ total_other_avian   <i64> 0, None, 11, None, 4, None, 0, None, None, None
$ total_misc          <i64> 0, None, 0, None, 0, None, 0, None, None, None
$ first_observed      <str> '2000-05-11', None, '2000-05-01', '2000-06-10', '2000-05-04', '2000-05-07', '2000-05-07', '2000-06-06', None, '2000-05-21'
$ last_observed       <str> '2000-08-05', None, '2000-08-19', '2000-09-24', '2000-08-30', '2000-08-13', '2000-08-17', '2000-09-05', None, '2000-08-12'
$ first_nest          <str> '2000-05-26', None, '2000-05-16', '2000-06-17', '2000-05-28', '2000-05-31', '2000-05-28', '2000-06-06', '2000-06-08', '2000-06-01'
$ first_chick         <str> '2000-06-18', None, '2000-06-07', '2000-07-22', '2000-06-20', '2000-06-22', '2000-06-20', '2000-06-28', '2000-06-26', '2000-06-24'
$ first_fledge        <str> '2000-07-08', None, '2000-06-30', '2000-08-06', '2000-07-13', '2000-07-20', '2000-07-15', '2000-07-24', '2000-07-17', '2000-07-16'

The next chapter explains data types in more detail. For now, just take note
that there are multiple types (`i64`, `str`, and `f64` in the `terns` data
frame).

In contrast to the `.glimpse` method, the `.describe` method provides a
statistical summary of a data frame:

In [4]:
terns.describe()

shape: (9, 44)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ year      ┆ site_name ┆ site_name ┆ … ┆ last_obse ┆ first_nes ┆ first_chi ┆ first_fl │
│ ---       ┆ ---       ┆ ---       ┆ _2013_201 ┆   ┆ rved      ┆ t         ┆ ck        ┆ edge     │
│ str       ┆ f64       ┆ str       ┆ 8         ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆ ---       ┆   ┆ str       ┆ str       ┆ str       ┆ str      │
│           ┆           ┆           ┆ str       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 791.0     ┆ 791       ┆ 788       ┆ … ┆ 642       ┆ 602       ┆ 529       ┆ 404      │
│ null_coun ┆ 0.0       ┆ 0         ┆ 3         ┆ … ┆ 149       ┆ 189       ┆ 262       ┆ 387      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ 2013.0821 ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 74        ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ std       ┆ 6.037819  ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ min       ┆ 2000.0    ┆ ALAMEDA   ┆ Alameda   ┆ … ┆ 2000-07-2 ┆ 2000-05-0 ┆ 2000-05-2 ┆ 2000-06- │
│           ┆           ┆ POINT     ┆ Point     ┆   ┆ 1         ┆ 5         ┆ 8         ┆ 20       │
│ 25%       ┆ 2008.0    ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 50%       ┆ 2013.0    ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 75%       ┆ 2018.0    ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ max       ┆ 2023.0    ┆ VENICE    ┆ Venice    ┆ … ┆ 2023-09-2 ┆ 2023-07-2 ┆ 3000-06-0 ┆ 2022-06- │
│           ┆           ┆ BEACH     ┆ Beach     ┆   ┆ 2         ┆ 3         ┆ 2         ┆ 25       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### Summarizing Columns

You can select individual columns with **bracket notation**. Put the name of
the column in quotes and place that inside of square brackets `[]`. For
example, to select the `total_nests` column:

In [5]:
terns["total_nests"]

shape: (791,)
Series: 'total_nests' [i64]
[
	15
	20
	312
	3
	5
	…
	717
	44
	59
	48
	171
]

Polars provides a variety of methods to compute on columns. For instance, you
can use the `.mean` method to compute the mean:

In [6]:
terns["total_nests"].mean()

162.84546615581098

Similarly, you can use the `.min` method to compute the smallest value in a
column:

In [7]:
terns["total_nests"].min()

0

For columns of categories, statistics like means and minimums aren't defined.
Instead, it's often informative to count the number of observations of each
category. You can do this with the `.value_counts` method:

In [8]:
terns["year"].value_counts()

shape: (21, 2)
┌──────┬───────┐
│ year ┆ count │
│ ---  ┆ ---   │
│ i64  ┆ u32   │
╞══════╪═══════╡
│ 2017 ┆ 45    │
│ 2007 ┆ 37    │
│ 2018 ┆ 34    │
│ 2009 ┆ 40    │
│ 2019 ┆ 35    │
│ …    ┆ …     │
│ 2016 ┆ 43    │
│ 2020 ┆ 35    │
│ 2010 ┆ 40    │
│ 2015 ┆ 42    │
│ 2012 ┆ 41    │
└──────┴───────┘

## Working with Different Data Types

When we used the .glimpse method to get a structural summary of the California least tern data set, we can start to take away some information about the data being stored.

In [9]:
terns.glimpse()

Rows: 791
Columns: 43
$ year                <i64> 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000
$ site_name           <str> 'PITTSBURG POWER PLANT', 'ALBANY CENTRAL AVE', 'ALAMEDA POINT', 'KETTLEMAN CITY', 'OCEANO DUNES STATE VEHICULAR RECREATION AREA', 'RANCHO GUADALUPE DUNES PRESERVE', 'VANDENBERG SFB', 'SANTA CLARA RIVER MCGRATH STATE BEACH', 'ORMOND BEACH', 'NBVC POINT MUGU'
$ site_name_2013_2018 <str> 'Pittsburg Power Plant', 'NA_NO POLYGON', 'Alameda Point', 'Kettleman', 'Oceano Dunes State Vehicular Recreation Area', 'Rancho Guadalupe Dunes Preserve', 'Vandenberg AFB', 'Santa Clara River', 'Ormond Beach', 'NBVC Point Mugu'
$ site_name_1988_2001 <str> 'NA_2013_2018 POLYGON', 'Albany Central Avenue', 'NA_2013_2018 POLYGON', 'NA_2013_2018 POLYGON', 'NA_2013_2018 POLYGON', 'NA_2013_2018 POLYGON', 'NA_2013_2018 POLYGON', 'NA_2013_2018 POLYGON', 'NA_2013_2018 POLYGON', 'NA_2013_2018 POLYGON'
$ site_abbr           <str> 'PITT_POWER', 'AL_CENTAVE', 'ALAM_PT', 'KET_CTY', 'OCEANO_DUNES', 'RGDP', 'VAN_SFB', 'S_CLAR_MCG', 'ORMOND', 'PT_MUGU'
$ region_3            <str> 'S.F._BAY', 'S.F._BAY', 'S.F._BAY', 'KINGS', 'CENTRAL', 'CENTRAL', 'CENTRAL', 'SOUTHERN', 'SOUTHERN', 'SOUTHERN'
$ region_4            <str> 'S.F._BAY', 'S.F._BAY', 'S.F._BAY', 'KINGS', 'CENTRAL', 'CENTRAL', 'CENTRAL', 'VENTURA', 'VENTURA', 'VENTURA'
$ event               <str> 'LA_NINA', 'LA_NINA', 'LA_NINA', 'LA_NINA', 'LA_NINA', 'LA_NINA', 'LA_NINA', 'LA_NINA', 'LA_NINA', 'LA_NINA'
$ bp_min              <f64> 15.0, 6.0, 282.0, 2.0, 4.0, 9.0, 30.0, 21.0, 73.0, 166.0
$ bp_max              <f64> 15.0, 12.0, 301.0, 3.0, 5.0, 9.0, 32.0, 21.0, 73.0, 167.0
$ fl_min              <i64> 16, 1, 200, 1, 4, 17, 11, 9, 60, 64
$ fl_max              <i64> 18, 1, 230, 2, 4, 17, 11, 9, 65, 64
$ total_nests         <i64> 15, 20, 312, 3, 5, 9, 32, 22, 73, 252
$ nonpred_eggs        <i64> 3, None, 124, None, 2, 0, None, 4, 2, None
$ nonpred_chicks      <i64> 0, None, 81, 3, 0, 1, 27, 3, 0, None
$ nonpred_fl          <i64> 0, None, 2, 1, 0, 0, 0, None, 0, None
$ nonpred_ad          <i64> 0, None, 1, 6, 0, 0, 0, None, 0, None
$ pred_control        <str> None, None, None, None, None, None, None, None, None, None
$ pred_eggs           <i64> 4, None, 17, None, 0, None, 0, None, None, None
$ pred_chicks         <i64> 2, None, 0, None, 4, None, 3, None, None, None
$ pred_fl             <i64> 0, None, 0, None, 0, None, 0, None, None, None
$ pred_ad             <i64> 0, None, 0, None, 0, None, 0, None, None, None
$ pred_pefa           <str> 'N', None, 'N', None, 'N', None, 'N', None, 'N', None
$ pred_coy_fox        <str> 'N', None, 'N', None, 'N', None, 'N', None, 'N', None
$ pred_meso           <str> 'N', None, 'N', None, 'N', None, 'N', None, 'Y', None
$ pred_owlspp         <str> 'N', None, 'N', None, 'N', None, 'N', None, 'N', None
$ pred_corvid         <str> 'Y', None, 'N', None, 'N', None, 'N', None, 'N', None
$ pred_other_raptor   <str> 'Y', None, 'Y', None, 'N', None, 'Y', None, 'Y', None
$ pred_other_avian    <str> 'N', None, 'Y', None, 'Y', None, 'N', None, 'N', None
$ pred_misc           <str> 'N', None, 'N', None, 'N', None, 'N', None, 'N', None
$ total_pefa          <i64> 0, None, 0, None, 0, None, 0, None, None, None
$ total_coy_fox       <i64> 0, None, 0, None, 0, None, 0, None, None, None
$ total_meso          <i64> 0, None, 0, None, 0, None, 0, None, None, None
$ total_owlspp        <i64> 0, None, 0, None, 0, None, 0, None, None, None
$ total_corvid        <i64> 4, None, 0, None, 0, None, 0, None, None, None
$ total_other_raptor  <i64> 2, None, 6, None, 0, None, 3, None, None, None
$ total_other_avian   <i64> 0, None, 11, None, 4, None, 0, None, None, None
$ total_misc          <i64> 0, None, 0, None, 0, None, 0, None, None, None
$ first_observed      <str> '2000-05-11', None, '2000-05-01', '2000-06-10', '2000-05-04', '2000-05-07', '2000-05-07', '2000-06-06', None, '2000-05-21'
$ last_observed       <str> '2000-08-05', None, '2000-08-19', '2000-09-24', '2000-08-30', '2000-08-13', '2000-08-17', '2000-09-05', None, '2000-08-12'
$ first_nest          <str> '2000-05-26', None, '2000-05-16', '2000-06-17', '2000-05-28', '2000-05-31', '2000-05-28', '2000-06-06', '2000-06-08', '2000-06-01'
$ first_chick         <str> '2000-06-18', None, '2000-06-07', '2000-07-22', '2000-06-20', '2000-06-22', '2000-06-20', '2000-06-28', '2000-06-26', '2000-06-24'
$ first_fledge        <str> '2000-07-08', None, '2000-06-30', '2000-08-06', '2000-07-13', '2000-07-20', '2000-07-15', '2000-07-24', '2000-07-17', '2000-07-16'

The first two rows describe the shape of the data set. After that, each row
lists a column name, the type of data in that column, and that column's first
few values. For instance, the `site_name` column contains `str`, or string,
data. This is why we spent so much time learning about different data types. Data frames usually have a mix of several different data types, and depending on the type, we can do different things with the data.

When doing data analysis, statisticians conventionally categorize data as one
of four types within two larger categories:

- Numeric
    - continuous (real or complex numbers)
    - discrete (integers)
- Categorical
    - nominal (categories with no ordering)
    - ordinal (categories with some ordering)

Here is a quick reminder about some of the different data types we have learned about:

Type      | Example         | Description
--------- | --------------- | -----------
`bool`    | `True`, `False` | Boolean values
`int`     | `-8`, `0`, `42` | Integers
`float`   | `-2.1`, `0.5`   | Real numbers
`complex` | `3j`, `1-2j`    | Complex numbers
`str`     | `"hi"`, `"2.1"` | Strings

We previously learned about the `type()` function, which allows us to determine datatypes:

In [10]:
print(type(True))
print(type(-8.3))

<class 'bool'>
<class 'float'>

We can also use another function, `isinstance()` to test whether a value is of a particular class. The following tests if `5` is a string:

In [11]:
isinstance(5, str)

False

### Series

A **series** is an ordered, one-dimensional data structure. Series are a
fundamental data structure in Polars, because each column in a data frame is a
series.

For example, in the California least tern data set, the `site_name` column is a
series. Take a look at the first few elements with its `.head` method:

In [12]:
terns["site_name"].head()

shape: (10,)
Series: 'site_name' [str]
[
	"PITTSBURG POWER PLANT"
	"ALBANY CENTRAL AVE"
	"ALAMEDA POINT"
	"KETTLEMAN CITY"
	"OCEANO DUNES STATE VEHICULAR R…
	"RANCHO GUADALUPE DUNES PRESERV…
	"VANDENBERG SFB"
	"SANTA CLARA RIVER MCGRATH STAT…
	"ORMOND BEACH"
	"NBVC POINT MUGU"
]

Series and data frames have many attributes and methods in common; the `.head`
method is one of these.

Notice that the elements of the `site_name` series are all strings. Unlike a
list, in a series, all elements must be of the same type, so we say series are
**homogeneous**. A series can contain strings, integers, decimal numbers, or
any of several other types of data, but not a mix of these all at once.

The other columns in the least tern data are also series. For instance, the
`year` column is a series of integers:

In [13]:
terns["year"]

shape: (791,)
Series: 'year' [i64]
[
	2000
	2000
	2000
	2000
	2000
	…
	2023
	2023
	2023
	2023
	2023
]

Series can contain any number of elements, including 0 or 1 element. You can
check the number of elements, or length, of a series with Python's built-in
`len` function:

In [14]:
len(terns["year"])

791

### Creating Series

Sometimes you’ll want to create series by manually inputting data, perhaps
because your data set isn't digitized or because you want a toy data set to
test out some code. You can create a series from a list (or other sequence)
with the `pl.Series` function:

In [15]:
pl.Series([1, 2, 19, -3])

shape: (4,)
Series: '' [i64]
[
	1
	2
	19
	-3
]

In [16]:
pl.Series(["hi", "hello"])

shape: (2,)
Series: '' [str]
[
	"hi"
	"hello"
]

The Polars documentation recommends setting a name for every series. To do this
with `pl.Series`, pass the name as the first argument and the elements as the
second argument:

In [17]:
pl.Series("tens", [10, 20, 30])

shape: (3,)
Series: 'tens' [i64]
[
	10
	20
	30
]

Polars will print the name when you print the series and will use the name as a
column name if you put the series in a data frame. You can get or set the name
on a series through the `.name` attribute:

In [18]:
x = pl.Series("tens", [10, 20, 30])
x.name

'tens'

By default, Polars infers the data type of a series' elements from the first
element. This can lead to errors you might not expect:

In [19]:
pl.Series([1, 9.2, 2.3])

TypeError: unexpected value while building Series of type Int64; found value of type Float64: 9.2

Hint: Try setting `strict=False` to allow passing data with mixed types.

You can explicitly specify a data type for a series with the `pl.Series`
function's third parameter, `dtype`:

In [20]:
pl.Series([1, 9.2, 2.3], dtype = float)

shape: (3,)
Series: '' [f64]
[
	1.0
	9.2
	2.3
]

Polars uses its own data types for series elements, so that:

* It can efficiently support types of data that are not built into Python, such
  as categorical data.
* Every numeric type has an explicit **bit size**: the number of bits of memory
  necessary to store an element. Bit sizes appear as suffixes in the name of
  the type. For instance, `Float32` stores a floating point number in 32 bits.
* A special value, `null`, can be present in any series to indicate missing
  data. We'll explain `null` in {ref}`sec-special-values`.

When you create or access the elements of a series, Polars silently converts
between its types and Python's built-in types. Some of the Polars types and
their Python equivalents are listed in the following table:

| Type                      | Python Equivalent | Description                        |
|---------------------------|-------------------|------------------------------------|
| Boolean                   | bool              | Boolean values                     |
| Int8, Int16, Int32, Int64 | int               | Integers                           |
| Float32, Float64          | float             | Real numbers (base-2 floating point) |
| Not yet supported         | complex           | Complex numbers                    |
| String                    | str               | Strings                            |
| Categorical, Enum         | No equivalent     | Categorical data                   |

The Polars documentation has [the complete list](https://docs.pola.rs/user-guide/concepts/data-types-and-structures/#appendix-full-data-types-table).

If you call Python's `type` function on a data structure, it returns the type
of the data structure:

In [21]:
type(terns["site_name"])

polars.series.series.Series

For a series, you can get the element type with the `.dtype` attribute:

In [22]:
terns["site_name"].dtype

String

### Categorical Data

A feature is **categorical** if it measures a qualitative category. For
example, the genres `rock`, `blues`, `alternative`, `folk`, `pop` are
categories.

Polars uses the `Categorical` and `Enum` data types to represent categorical
data. Visualizations and statistical models sometimes treat categorical data
differently than other data types, so it's important to make sure you have the
right data type.

When it reads a data set, Polars usually can't tell which features are
categorical. That means identifying and converting the categorical features is
up to you. For beginners, it can be difficult to understand whether a feature
is categorical or not. The key is to think about whether you want to use the
feature to divide the data into groups.

For example, if you want to know how many songs are in the `rock` genre, you
first need to divide the songs by genre, and then count the number of songs in
each group (or at least the `rock` group).

As a second example, months recorded as numbers can be categorical or not,
depending on how you want to use them. You might want to treat them as
categorical (for example, to compute max rainfall in each month) or you might
want to treat them as numbers (for example, to compute the number of months
time between two events).

**The bottom line is that you have to think about what you'll be doing in the
analysis**. In some cases, you might treat a feature as categorical only for part
of the analysis.

Let's think about which features are categorical in least terns data set. To
refresh your memory of what's in the data set, take a look at the structural
summary:

In [23]:
terns.glimpse()

Rows: 791
Columns: 43
$ year                <i64> 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000
$ site_name           <str> 'PITTSBURG POWER PLANT', 'ALBANY CENTRAL AVE', 'ALAMEDA POINT', 'KETTLEMAN CITY', 'OCEANO DUNES STATE VEHICULAR RECREATION AREA', 'RANCHO GUADALUPE DUNES PRESERVE', 'VANDENBERG SFB', 'SANTA CLARA RIVER MCGRATH STATE BEACH', 'ORMOND BEACH', 'NBVC POINT MUGU'
$ site_name_2013_2018 <str> 'Pittsburg Power Plant', 'NA_NO POLYGON', 'Alameda Point', 'Kettleman', 'Oceano Dunes State Vehicular Recreation Area', 'Rancho Guadalupe Dunes Preserve', 'Vandenberg AFB', 'Santa Clara River', 'Ormond Beach', 'NBVC Point Mugu'
$ site_name_1988_2001 <str> 'NA_2013_2018 POLYGON', 'Albany Central Avenue', 'NA_2013_2018 POLYGON', 'NA_2013_2018 POLYGON', 'NA_2013_2018 POLYGON', 'NA_2013_2018 POLYGON', 'NA_2013_2018 POLYGON', 'NA_2013_2018 POLYGON', 'NA_2013_2018 POLYGON', 'NA_2013_2018 POLYGON'
$ site_abbr           <str> 'PITT_POWER', 'AL_CENTAVE', 'ALAM_PT', 'KET_CTY', 'OCEANO_DUNES', 'RGDP', 'VAN_SFB', 'S_CLAR_MCG', 'ORMOND', 'PT_MUGU'
$ region_3            <str> 'S.F._BAY', 'S.F._BAY', 'S.F._BAY', 'KINGS', 'CENTRAL', 'CENTRAL', 'CENTRAL', 'SOUTHERN', 'SOUTHERN', 'SOUTHERN'
$ region_4            <str> 'S.F._BAY', 'S.F._BAY', 'S.F._BAY', 'KINGS', 'CENTRAL', 'CENTRAL', 'CENTRAL', 'VENTURA', 'VENTURA', 'VENTURA'
$ event               <str> 'LA_NINA', 'LA_NINA', 'LA_NINA', 'LA_NINA', 'LA_NINA', 'LA_NINA', 'LA_NINA', 'LA_NINA', 'LA_NINA', 'LA_NINA'
$ bp_min              <f64> 15.0, 6.0, 282.0, 2.0, 4.0, 9.0, 30.0, 21.0, 73.0, 166.0
$ bp_max              <f64> 15.0, 12.0, 301.0, 3.0, 5.0, 9.0, 32.0, 21.0, 73.0, 167.0
$ fl_min              <i64> 16, 1, 200, 1, 4, 17, 11, 9, 60, 64
$ fl_max              <i64> 18, 1, 230, 2, 4, 17, 11, 9, 65, 64
$ total_nests         <i64> 15, 20, 312, 3, 5, 9, 32, 22, 73, 252
$ nonpred_eggs        <i64> 3, None, 124, None, 2, 0, None, 4, 2, None
$ nonpred_chicks      <i64> 0, None, 81, 3, 0, 1, 27, 3, 0, None
$ nonpred_fl          <i64> 0, None, 2, 1, 0, 0, 0, None, 0, None
$ nonpred_ad          <i64> 0, None, 1, 6, 0, 0, 0, None, 0, None
$ pred_control        <str> None, None, None, None, None, None, None, None, None, None
$ pred_eggs           <i64> 4, None, 17, None, 0, None, 0, None, None, None
$ pred_chicks         <i64> 2, None, 0, None, 4, None, 3, None, None, None
$ pred_fl             <i64> 0, None, 0, None, 0, None, 0, None, None, None
$ pred_ad             <i64> 0, None, 0, None, 0, None, 0, None, None, None
$ pred_pefa           <str> 'N', None, 'N', None, 'N', None, 'N', None, 'N', None
$ pred_coy_fox        <str> 'N', None, 'N', None, 'N', None, 'N', None, 'N', None
$ pred_meso           <str> 'N', None, 'N', None, 'N', None, 'N', None, 'Y', None
$ pred_owlspp         <str> 'N', None, 'N', None, 'N', None, 'N', None, 'N', None
$ pred_corvid         <str> 'Y', None, 'N', None, 'N', None, 'N', None, 'N', None
$ pred_other_raptor   <str> 'Y', None, 'Y', None, 'N', None, 'Y', None, 'Y', None
$ pred_other_avian    <str> 'N', None, 'Y', None, 'Y', None, 'N', None, 'N', None
$ pred_misc           <str> 'N', None, 'N', None, 'N', None, 'N', None, 'N', None
$ total_pefa          <i64> 0, None, 0, None, 0, None, 0, None, None, None
$ total_coy_fox       <i64> 0, None, 0, None, 0, None, 0, None, None, None
$ total_meso          <i64> 0, None, 0, None, 0, None, 0, None, None, None
$ total_owlspp        <i64> 0, None, 0, None, 0, None, 0, None, None, None
$ total_corvid        <i64> 4, None, 0, None, 0, None, 0, None, None, None
$ total_other_raptor  <i64> 2, None, 6, None, 0, None, 3, None, None, None
$ total_other_avian   <i64> 0, None, 11, None, 4, None, 0, None, None, None
$ total_misc          <i64> 0, None, 0, None, 0, None, 0, None, None, None
$ first_observed      <str> '2000-05-11', None, '2000-05-01', '2000-06-10', '2000-05-04', '2000-05-07', '2000-05-07', '2000-06-06', None, '2000-05-21'
$ last_observed       <str> '2000-08-05', None, '2000-08-19', '2000-09-24', '2000-08-30', '2000-08-13', '2000-08-17', '2000-09-05', None, '2000-08-12'
$ first_nest          <str> '2000-05-26', None, '2000-05-16', '2000-06-17', '2000-05-28', '2000-05-31', '2000-05-28', '2000-06-06', '2000-06-08', '2000-06-01'
$ first_chick         <str> '2000-06-18', None, '2000-06-07', '2000-07-22', '2000-06-20', '2000-06-22', '2000-06-20', '2000-06-28', '2000-06-26', '2000-06-24'
$ first_fledge        <str> '2000-07-08', None, '2000-06-30', '2000-08-06', '2000-07-13', '2000-07-20', '2000-07-15', '2000-07-24', '2000-07-17', '2000-07-16'

The `site_name`, `site_abbr`, and `event` columns are all examples of
categorical data. The `region_` columns and some of the `pred_` columns also
contain categorical data.

One way to check whether a feature is useful for grouping (and thus effectively
categorical) is to count the number of times each value appears. For a series,
you can do this with the `.value_counts` method. For instance, to count the
number of times each category of `event` appears:

In [24]:
terns["event"].value_counts()

shape: (3, 2)
┌─────────┬───────┐
│ event   ┆ count │
│ ---     ┆ ---   │
│ str     ┆ u32   │
╞═════════╪═══════╡
│ EL_NINO ┆ 120   │
│ NEUTRAL ┆ 413   │
│ LA_NINA ┆ 258   │
└─────────┴───────┘

Features with only a few unique values, repeated many times, are ideal for
grouping. Numerical features, like `total_nests`, usually aren't good for
grouping, both because of what they measure and because they tend to have many
unique values, which leads to very small groups.

The `year` column can be treated as categorical or quantitative data. It's easy
to imagine grouping observations by year, but years are also numerical: they
have an order and we might want to do math on them. The most appropriate type
for `year` depends on how we want to use it for analysis.

You can cast a column to the `Categorical` type with the `.cast` method. Try
this for the `event` column:

In [25]:
event = terns["event"].cast(pl.Categorical)
event

shape: (791,)
Series: 'event' [cat]
[
	"LA_NINA"
	"LA_NINA"
	"LA_NINA"
	"LA_NINA"
	"LA_NINA"
	…
	"LA_NINA"
	"LA_NINA"
	"LA_NINA"
	"LA_NINA"
	"LA_NINA"
]

Polars organizes attributes and methods for categorical data under the `.cat`
attribute of series. These raise errors if the element type of the series is
not `Categorical` (or `Enum`). You can get the categories of a categorical
series with the `.cat.get_categories` method:

In [26]:
event.cat.get_categories()

shape: (3,)
Series: 'event' [str]
[
	"LA_NINA"
	"NEUTRAL"
	"EL_NINO"
]

A categorical series remembers all possible categories even if you take a
subset where some of the categories aren't present:

In [27]:
event[:3]

shape: (3,)
Series: 'event' [cat]
[
	"LA_NINA"
	"LA_NINA"
	"LA_NINA"
]

In [28]:
event[:3].cat.get_categories()

shape: (3,)
Series: 'event' [str]
[
	"LA_NINA"
	"NEUTRAL"
	"EL_NINO"
]

This is one way the `Categorical` type is different from the `String` type, and
ensures that when you, for example, plot a categorical series, missing
categories are represented.

### Broadcasting

If you use an arithmetic operator on a series, Polars **broadcasts** the
operation to each element:

In [29]:
x = pl.Series([1, 3, 0])
x - 3

shape: (3,)
Series: '' [i64]
[
	-2
	0
	-3
]

The result is the same as if you had applied the operation element-by-element.
That is:

In [30]:
pl.Series([1 - 3, 3 - 3, 0 - 3])

shape: (3,)
Series: '' [i64]
[
	-2
	0
	-3
]

Most NumPy (and SciPy) functions also broadcast. For instance:

In [31]:
import numpy as np

x = pl.Series([1.0, 3.0, 0.0, np.pi])
np.sin(x)

shape: (4,)
Series: '' [f64]
[
	0.841471
	0.14112
	0.0
	1.2246e-16
]

Some examples of functions that broadcast are `np.sin`, `np.cos`, `np.tan`,
`np.log`, `np.exp`, and `np.sqrt`.

NumPy functions that combine or aggregate values usually don't broadcast. For
example, `np.sum`, `np.mean`, and `np.median` don't broadcast.

Generally, you should:

* Use broadcasting with data structures that support it, such as series and
  NumPy arrays (explained in {ref}`sec-numpy-arrays`).
* Use comprehensions with lists and Python's other built-in data structures
  (explained in {ref}`sec-built-in-data-structures`).


A function can broadcast across multiple arguments. To demonstrate this,
suppose we want to estimate number of nests per breeding pair for the least
terns data. The `total_nests` column contains the total number of nests at each
site, and the `bp_max` column contains the maximum reported number of breeding
pairs. So to compute nests per breeding pair:

In [32]:
terns["total_nests"] / terns["bp_max"]

shape: (791,)
Series: 'total_nests' [f64]
[
	1.0
	1.666667
	1.036545
	1.0
	1.0
	…
	1.113354
	1.157895
	1.092593
	1.170732
	1.036364
]

The elements are paired up and divided according to their positions. Notice
that the result is a `Float64` series. The `total_nests` column is an `Int64`
series, so besides broadcasting, the example also demonstrates that Series are
subject to implicit coercion (introduced in {ref}`sec-coercion-casting`).

If you try to broadcast a function across two series of different lengths,
Polars raises an error:

In [33]:
x = pl.Series([1, 2])
y = pl.Series([9, 8, 7])
x - y

InvalidOperationError: cannot do arithmetic operation on series of different lengths: got 2 and 3

### Missing Values

Most data sets are not perfect. Some data is not usable, some is missing for one reason or another, etc. In the least terns data set, notice that some of the entries are `null`. For
instance, look at the second element of the `nonpred_eggs` column:

In [34]:
terns.head()

shape: (5, 43)
┌──────┬────────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ year ┆ site_name  ┆ site_name_ ┆ site_name_ ┆ … ┆ last_obser ┆ first_nes ┆ first_chi ┆ first_fle │
│ ---  ┆ ---        ┆ 2013_2018  ┆ 1988_2001  ┆   ┆ ved        ┆ t         ┆ ck        ┆ dge       │
│ i64  ┆ str        ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ ---       │
│      ┆            ┆ str        ┆ str        ┆   ┆ str        ┆ str       ┆ str       ┆ str       │
╞══════╪════════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2000 ┆ PITTSBURG  ┆ Pittsburg  ┆ NA_2013_20 ┆ … ┆ 2000-08-05 ┆ 2000-05-2 ┆ 2000-06-1 ┆ 2000-07-0 │
│      ┆ POWER      ┆ Power      ┆ 18 POLYGON ┆   ┆            ┆ 6         ┆ 8         ┆ 8         │
│      ┆ PLANT      ┆ Plant      ┆            ┆   ┆            ┆           ┆           ┆           │
│ 2000 ┆ ALBANY     ┆ NA_NO      ┆ Albany     ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│      ┆ CENTRAL    ┆ POLYGON    ┆ Central    ┆   ┆            ┆           ┆           ┆           │
│      ┆ AVE        ┆            ┆ Avenue     ┆   ┆            ┆           ┆           ┆           │
│ 2000 ┆ ALAMEDA    ┆ Alameda    ┆ NA_2013_20 ┆ … ┆ 2000-08-19 ┆ 2000-05-1 ┆ 2000-06-0 ┆ 2000-06-3 │
│      ┆ POINT      ┆ Point      ┆ 18 POLYGON ┆   ┆            ┆ 6         ┆ 7         ┆ 0         │
│ 2000 ┆ KETTLEMAN  ┆ Kettleman  ┆ NA_2013_20 ┆ … ┆ 2000-09-24 ┆ 2000-06-1 ┆ 2000-07-2 ┆ 2000-08-0 │
│      ┆ CITY       ┆            ┆ 18 POLYGON ┆   ┆            ┆ 7         ┆ 2         ┆ 6         │
│ 2000 ┆ OCEANO     ┆ Oceano     ┆ NA_2013_20 ┆ … ┆ 2000-08-30 ┆ 2000-05-2 ┆ 2000-06-2 ┆ 2000-07-1 │
│      ┆ DUNES      ┆ Dunes      ┆ 18 POLYGON ┆   ┆            ┆ 8         ┆ 0         ┆ 3         │
│      ┆ STATE      ┆ State      ┆            ┆   ┆            ┆           ┆           ┆           │
│      ┆ VEHICULAR  ┆ Vehicular  ┆            ┆   ┆            ┆           ┆           ┆           │
│      ┆ R…         ┆ R…         ┆            ┆   ┆            ┆           ┆           ┆           │
└──────┴────────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

Polars uses `null`, called the **missing value**, to represent missing entries
in a data set. It’s implied that the entries are missing due to how the data
was collected, although there are exceptions. As an example, imagine the data
came from a survey, and respondents chose not to answer some questions. In the
data set, their answers for those questions can be recorded as `null`.

The missing value `null` is a chameleon: it can be of an element of any type in
a series. Polars implicitly converts `null` to and from `None` when you get or
set an element in a series. This means you can use `None` to create a series
with `null` elements:

In [35]:
x = pl.Series([1, 2, None])
x

shape: (3,)
Series: '' [i64]
[
	1
	2
	null
]

And you get back `None` if you access a `null` element:

In [36]:
terns["nonpred_eggs"][1]

The missing value `null` is also contagious: it represents an unknown quantity,
so computing on it usually produces another missing value. The idea is that if
the inputs to a computation are unknown, generally so is the output:

In [37]:
x - 3

shape: (3,)
Series: '' [i64]
[
	-2
	-1
	null
]

Polars makes an exception for aggregation functions, which automatically filter
out missing values:

In [38]:
x.mean()

1.5

You can use the `.is_null` method to test if elements of a series are `null`:

In [39]:
x.is_null()

shape: (3,)
Series: '' [bool]
[
	false
	false
	true
]

Polars also provides an `.is_not_null` method and a `.fill_null` method to fill
missing values with a different value.

### Selecting Columns

An excellent starting point for selecting and transforming columns in a data frame is the `.select` method. We already learned how to select a single column by name with the indexing operator `[]`, but the `.select` method is much more flexible. You can use it to select multiple columns at once, by name or type, and can transform or rename them.

As with the indexing operator, you can use `.select` to select a single column by providing the column name as an argument. Here's an example (with `.head` to limit the output):

In [40]:
terns.select("year").head()

shape: (5, 1)
┌──────┐
│ year │
│ ---  │
│ i64  │
╞══════╡
│ 2000 │
│ 2000 │
│ 2000 │
│ 2000 │
│ 2000 │
└──────┘

Unlike the indexing operator, `.select` returns a data frame rather than a series.

You can also select multiple columns this way:

In [41]:
terns.select("year", "site_name").head()

shape: (5, 2)
┌──────┬─────────────────────────────────┐
│ year ┆ site_name                       │
│ ---  ┆ ---                             │
│ i64  ┆ str                             │
╞══════╪═════════════════════════════════╡
│ 2000 ┆ PITTSBURG POWER PLANT           │
│ 2000 ┆ ALBANY CENTRAL AVE              │
│ 2000 ┆ ALAMEDA POINT                   │
│ 2000 ┆ KETTLEMAN CITY                  │
│ 2000 ┆ OCEANO DUNES STATE VEHICULAR R… │
└──────┴─────────────────────────────────┘

The `.select` method is flexible because it can evaluate a **Polars expression**: instructions for how to select or transform data. One way to create an expression is with the `pl.col` function, which represents a column or set of columns. So another way to select the `year` and `site_name` column from the least terns data is:

In [42]:
terns.select(
    pl.col("year", "site_name")
).head()

shape: (5, 2)
┌──────┬─────────────────────────────────┐
│ year ┆ site_name                       │
│ ---  ┆ ---                             │
│ i64  ┆ str                             │
╞══════╪═════════════════════════════════╡
│ 2000 ┆ PITTSBURG POWER PLANT           │
│ 2000 ┆ ALBANY CENTRAL AVE              │
│ 2000 ┆ ALAMEDA POINT                   │
│ 2000 ┆ KETTLEMAN CITY                  │
│ 2000 ┆ OCEANO DUNES STATE VEHICULAR R… │
└──────┴─────────────────────────────────┘

An advantage of using `pl.col` is that you're not limited to selecting columns by name: you can also select columns by type. Here's how to get only the `Int64` and `Float64` columns in the least terns data:

In [43]:
terns.select(
    pl.col(pl.Int64, pl.Float64)
).head()

shape: (5, 22)
┌──────┬────────┬────────┬────────┬───┬──────────────┬────────────────┬───────────────┬────────────┐
│ year ┆ bp_min ┆ bp_max ┆ fl_min ┆ … ┆ total_corvid ┆ total_other_ra ┆ total_other_a ┆ total_misc │
│ ---  ┆ ---    ┆ ---    ┆ ---    ┆   ┆ ---          ┆ ptor           ┆ vian          ┆ ---        │
│ i64  ┆ f64    ┆ f64    ┆ i64    ┆   ┆ i64          ┆ ---            ┆ ---           ┆ i64        │
│      ┆        ┆        ┆        ┆   ┆              ┆ i64            ┆ i64           ┆            │
╞══════╪════════╪════════╪════════╪═══╪══════════════╪════════════════╪═══════════════╪════════════╡
│ 2000 ┆ 15.0   ┆ 15.0   ┆ 16     ┆ … ┆ 4            ┆ 2              ┆ 0             ┆ 0          │
│ 2000 ┆ 6.0    ┆ 12.0   ┆ 1      ┆ … ┆ null         ┆ null           ┆ null          ┆ null       │
│ 2000 ┆ 282.0  ┆ 301.0  ┆ 200    ┆ … ┆ 0            ┆ 6              ┆ 11            ┆ 0          │
│ 2000 ┆ 2.0    ┆ 3.0    ┆ 1      ┆ … ┆ null         ┆ null           ┆ null          ┆ null       │
│ 2000 ┆ 4.0    ┆ 5.0    ┆ 4      ┆ … ┆ 0            ┆ 0              ┆ 4             ┆ 0          │
└──────┴────────┴────────┴────────┴───┴──────────────┴────────────────┴───────────────┴────────────┘

Selecting columns this way is useful for doing things like computing summaries of only numeric columns. In fact, to compute widely-used summaries, like the mean, all you need to do is call the corresponding method on the Polars expression:

In [44]:
terns.select(
    pl.col(pl.Int64, pl.Float64).mean()
).head()

shape: (1, 22)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ year      ┆ bp_min    ┆ bp_max    ┆ fl_min    ┆ … ┆ total_cor ┆ total_oth ┆ total_oth ┆ total_mi │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ vid       ┆ er_raptor ┆ er_avian  ┆ sc       │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2013.0821 ┆ 129.31992 ┆ 151.04342 ┆ 40.815148 ┆ … ┆ 7.961538  ┆ 1.711538  ┆ 8.897959  ┆ 6.566038 │
│ 74        ┆ 3         ┆ 3         ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

A third way to select columns with `pl.col` is with a pattern. Patterns are strings, and must begin with a caret `^` and end with a dollar sign `$`. Within a pattern, you can use `.*` as a wild card that matches any characters.

As motivation to demonstrate patterns, most of the columns with names that start with `pred_` are categorical but currently have string elements. It would be good to cast them to the `Categorical` type. To begin, select all of the columns with names that start with `pred_`:

**Note**: Technically, Polars' patterns are regular expressions, a widely-used language for describing patterns in text. You can learn more about regular expressions in the [Date & String Processing](https://ucdavisdatalab.github.io/workshop_intermediate_python/chapters/01_string-date-processing.html) chapter of DataLab's Intermediate Python workshop reader.

In [45]:
terns.select(
    pl.col("^pred_.*$")
).head()

shape: (5, 13)
┌────────────┬───────────┬───────────┬─────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ pred_contr ┆ pred_eggs ┆ pred_chic ┆ pred_fl ┆ … ┆ pred_corv ┆ pred_othe ┆ pred_othe ┆ pred_misc │
│ ol         ┆ ---       ┆ ks        ┆ ---     ┆   ┆ id        ┆ r_raptor  ┆ r_avian   ┆ ---       │
│ ---        ┆ i64       ┆ ---       ┆ i64     ┆   ┆ ---       ┆ ---       ┆ ---       ┆ str       │
│ str        ┆           ┆ i64       ┆         ┆   ┆ str       ┆ str       ┆ str       ┆           │
╞════════════╪═══════════╪═══════════╪═════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ null       ┆ 4         ┆ 2         ┆ 0       ┆ … ┆ Y         ┆ Y         ┆ N         ┆ N         │
│ null       ┆ null      ┆ null      ┆ null    ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ null       ┆ 17        ┆ 0         ┆ 0       ┆ … ┆ N         ┆ Y         ┆ Y         ┆ N         │
│ null       ┆ null      ┆ null      ┆ null    ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ null       ┆ 0         ┆ 4         ┆ 0       ┆ … ┆ N         ┆ N         ┆ Y         ┆ N         │
└────────────┴───────────┴───────────┴─────────┴───┴───────────┴───────────┴───────────┴───────────┘

There are a few columns in the result, such as `pred_eggs`, with `Int64` elements. These columns aren't categorical, so we should exclude them before casting. You can exclude columns from an expression with the `.exclude` method:

In [46]:
terns.select(
    pl.col("^pred_.*$").exclude(pl.Int64).cast(pl.Categorical)
).head()

shape: (5, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ pred_cont ┆ pred_pefa ┆ pred_coy_ ┆ pred_meso ┆ … ┆ pred_corv ┆ pred_othe ┆ pred_othe ┆ pred_mis │
│ rol       ┆ ---       ┆ fox       ┆ ---       ┆   ┆ id        ┆ r_raptor  ┆ r_avian   ┆ c        │
│ ---       ┆ cat       ┆ ---       ┆ cat       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ cat       ┆           ┆ cat       ┆           ┆   ┆ cat       ┆ cat       ┆ cat       ┆ cat      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ null      ┆ N         ┆ N         ┆ N         ┆ … ┆ Y         ┆ Y         ┆ N         ┆ N        │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ null      ┆ N         ┆ N         ┆ N         ┆ … ┆ N         ┆ Y         ┆ Y         ┆ N        │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ null      ┆ N         ┆ N         ┆ N         ┆ … ┆ N         ┆ N         ┆ Y         ┆ N        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

To make this change permanent, we need to reassign the `terns` data frame. The `.select` method only returns the selected columns, so assigning the result to `terns` would mean losing all of the other columns.

Instead of using `.select`, you can use `.with_columns` to transform some columns but return all of the columns. In all other respects, `.with_columns` works the same way as `.select`. So to make the cast permanent:

In [47]:
terns = terns.with_columns(
    pl.col("^pred_.*$").exclude(pl.Int64).cast(pl.Categorical)
)

terns.head()

shape: (5, 43)
┌──────┬────────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ year ┆ site_name  ┆ site_name_ ┆ site_name_ ┆ … ┆ last_obser ┆ first_nes ┆ first_chi ┆ first_fle │
│ ---  ┆ ---        ┆ 2013_2018  ┆ 1988_2001  ┆   ┆ ved        ┆ t         ┆ ck        ┆ dge       │
│ i64  ┆ str        ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ ---       │
│      ┆            ┆ str        ┆ str        ┆   ┆ str        ┆ str       ┆ str       ┆ str       │
╞══════╪════════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2000 ┆ PITTSBURG  ┆ Pittsburg  ┆ NA_2013_20 ┆ … ┆ 2000-08-05 ┆ 2000-05-2 ┆ 2000-06-1 ┆ 2000-07-0 │
│      ┆ POWER      ┆ Power      ┆ 18 POLYGON ┆   ┆            ┆ 6         ┆ 8         ┆ 8         │
│      ┆ PLANT      ┆ Plant      ┆            ┆   ┆            ┆           ┆           ┆           │
│ 2000 ┆ ALBANY     ┆ NA_NO      ┆ Albany     ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│      ┆ CENTRAL    ┆ POLYGON    ┆ Central    ┆   ┆            ┆           ┆           ┆           │
│      ┆ AVE        ┆            ┆ Avenue     ┆   ┆            ┆           ┆           ┆           │
│ 2000 ┆ ALAMEDA    ┆ Alameda    ┆ NA_2013_20 ┆ … ┆ 2000-08-19 ┆ 2000-05-1 ┆ 2000-06-0 ┆ 2000-06-3 │
│      ┆ POINT      ┆ Point      ┆ 18 POLYGON ┆   ┆            ┆ 6         ┆ 7         ┆ 0         │
│ 2000 ┆ KETTLEMAN  ┆ Kettleman  ┆ NA_2013_20 ┆ … ┆ 2000-09-24 ┆ 2000-06-1 ┆ 2000-07-2 ┆ 2000-08-0 │
│      ┆ CITY       ┆            ┆ 18 POLYGON ┆   ┆            ┆ 7         ┆ 2         ┆ 6         │
│ 2000 ┆ OCEANO     ┆ Oceano     ┆ NA_2013_20 ┆ … ┆ 2000-08-30 ┆ 2000-05-2 ┆ 2000-06-2 ┆ 2000-07-1 │
│      ┆ DUNES      ┆ Dunes      ┆ 18 POLYGON ┆   ┆            ┆ 8         ┆ 0         ┆ 3         │
│      ┆ STATE      ┆ State      ┆            ┆   ┆            ┆           ┆           ┆           │
│      ┆ VEHICULAR  ┆ Vehicular  ┆            ┆   ┆            ┆           ┆           ┆           │
│      ┆ R…         ┆ R…         ┆            ┆   ┆            ┆           ┆           ┆           │
└──────┴────────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In general, choose:

* `.select` if you only want to get back the selected columns
* `.with_columns` if you want get back all of the columns

The `.select` method is also useful for testing expressions before switching to
the `.with_columns` method.

You can use columns to transform other columns. As a final example, suppose we want to compute eggs per breeding pair and nests per breeding pair for the least terns data. Non-predated egg counts are in the `nonpred_eggs` column and nest counts are in the `total_nests` column. For now, we'll use the maximum reported breeding pairs, `bp_max`, as the number of breeding pairs:

In [48]:
terns.select(
    pl.col("nonpred_eggs", "total_nests") / pl.col("bp_max")
).head()

shape: (5, 2)
┌──────────────┬─────────────┐
│ nonpred_eggs ┆ total_nests │
│ ---          ┆ ---         │
│ f64          ┆ f64         │
╞══════════════╪═════════════╡
│ 0.2          ┆ 1.0         │
│ null         ┆ 1.666667    │
│ 0.41196      ┆ 1.036545    │
│ null         ┆ 1.0         │
│ 0.4          ┆ 1.0         │
└──────────────┴─────────────┘

There's also a `bp_min` column with the minimum reported breeding pairs. To be thorough, we should compute the rates with both `bp_min` and `bp_max`, not just `bp_max`. We'll also need to rename the resulting columns, so that each column has a unique name. You can use the `.alias` method to rename a single column, or the `.name.prefix` and `.name.suffix` methods, respectively, to prefix or suffix a column's name. Let's add a suffix to the column names to identify which breeding pair column was used:

In [49]:
terns.select(
    (
        pl.col("nonpred_eggs", "total_nests") / pl.col("bp_max")
    ).name.suffix("_per_bp_max"),
    (
        pl.col("nonpred_eggs", "total_nests") / pl.col("bp_min")
    ).name.suffix("_per_bp_min")
).head()

shape: (5, 4)
┌────────────────────────┬────────────────────────┬────────────────────────┬───────────────────────┐
│ nonpred_eggs_per_bp_ma ┆ total_nests_per_bp_max ┆ nonpred_eggs_per_bp_mi ┆ total_nests_per_bp_mi │
│ x                      ┆ ---                    ┆ n                      ┆ n                     │
│ ---                    ┆ f64                    ┆ ---                    ┆ ---                   │
│ f64                    ┆                        ┆ f64                    ┆ f64                   │
╞════════════════════════╪════════════════════════╪════════════════════════╪═══════════════════════╡
│ 0.2                    ┆ 1.0                    ┆ 0.2                    ┆ 1.0                   │
│ null                   ┆ 1.666667               ┆ null                   ┆ 3.333333              │
│ 0.41196                ┆ 1.036545               ┆ 0.439716               ┆ 1.106383              │
│ null                   ┆ 1.0                    ┆ null                   ┆ 1.5                   │
│ 0.4                    ┆ 1.0                    ┆ 0.5                    ┆ 1.25                  │
└────────────────────────┴────────────────────────┴────────────────────────┴───────────────────────┘

### Filtering Rows

Filtering the rows of a data frame is the counterpart selecting columns. The `.filter` method filters rows based on one or more **conditions**: expressions that evaluate to a series of Boolean values.

As an example, suppose we want to find all sites in the least terns data where the number of nests in the `total_nests` column is greater than 5. Here's the code:

In [50]:
terns.filter(pl.col("total_nests") > 5).head()

shape: (5, 43)
┌──────┬────────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ year ┆ site_name  ┆ site_name_ ┆ site_name_ ┆ … ┆ last_obser ┆ first_nes ┆ first_chi ┆ first_fle │
│ ---  ┆ ---        ┆ 2013_2018  ┆ 1988_2001  ┆   ┆ ved        ┆ t         ┆ ck        ┆ dge       │
│ i64  ┆ str        ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ ---       │
│      ┆            ┆ str        ┆ str        ┆   ┆ str        ┆ str       ┆ str       ┆ str       │
╞══════╪════════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2000 ┆ PITTSBURG  ┆ Pittsburg  ┆ NA_2013_20 ┆ … ┆ 2000-08-05 ┆ 2000-05-2 ┆ 2000-06-1 ┆ 2000-07-0 │
│      ┆ POWER      ┆ Power      ┆ 18 POLYGON ┆   ┆            ┆ 6         ┆ 8         ┆ 8         │
│      ┆ PLANT      ┆ Plant      ┆            ┆   ┆            ┆           ┆           ┆           │
│ 2000 ┆ ALBANY     ┆ NA_NO      ┆ Albany     ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│      ┆ CENTRAL    ┆ POLYGON    ┆ Central    ┆   ┆            ┆           ┆           ┆           │
│      ┆ AVE        ┆            ┆ Avenue     ┆   ┆            ┆           ┆           ┆           │
│ 2000 ┆ ALAMEDA    ┆ Alameda    ┆ NA_2013_20 ┆ … ┆ 2000-08-19 ┆ 2000-05-1 ┆ 2000-06-0 ┆ 2000-06-3 │
│      ┆ POINT      ┆ Point      ┆ 18 POLYGON ┆   ┆            ┆ 6         ┆ 7         ┆ 0         │
│ 2000 ┆ RANCHO     ┆ Rancho     ┆ NA_2013_20 ┆ … ┆ 2000-08-13 ┆ 2000-05-3 ┆ 2000-06-2 ┆ 2000-07-2 │
│      ┆ GUADALUPE  ┆ Guadalupe  ┆ 18 POLYGON ┆   ┆            ┆ 1         ┆ 2         ┆ 0         │
│      ┆ DUNES      ┆ Dunes      ┆            ┆   ┆            ┆           ┆           ┆           │
│      ┆ PRESERV…   ┆ Preserv…   ┆            ┆   ┆            ┆           ┆           ┆           │
│ 2000 ┆ VANDENBERG ┆ Vandenberg ┆ NA_2013_20 ┆ … ┆ 2000-08-17 ┆ 2000-05-2 ┆ 2000-06-2 ┆ 2000-07-1 │
│      ┆ SFB        ┆ AFB        ┆ 18 POLYGON ┆   ┆            ┆ 8         ┆ 0         ┆ 5         │
└──────┴────────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

If we only want the site names, we can chain this with a call to `.select` and use the `.unique` method on the `site_name` column:

In [51]:
terns.filter(
    pl.col("total_nests") > 5
).select(
    pl.col("site_name").unique()
)

shape: (40, 1)
┌─────────────────────────────────┐
│ site_name                       │
│ ---                             │
│ str                             │
╞═════════════════════════════════╡
│ SAN ELIJO LAGOON ECOLOGICAL RE… │
│ SANTA CLARA RIVER MCGRATH STAT… │
│ SDIA LINDBERGH FIELD            │
│ VANDENBERG SFB                  │
│ BURRIS ISLAND                   │
│ …                               │
│ VENICE BEACH                    │
│ MISSION BAY FAA ISLAND          │
│ OCEANO DUNES STATE VEHICULAR R… │
│ BOLSA CHICA ECOLOGICAL RESERVE  │
│ EDEN LANDING ECOLOGICAL RESERV… │
└─────────────────────────────────┘

We can conclude that there are 40 sites that had at least 5 nests at some point.

### Logic Operators

In previous sessions, we learned about logic operators. Here, we get to see the utility of them. Series with Boolean elements, such as conditions, can be inverted or combined with logic operators. All of the logic operators broadcast to series elements. 

As a final example, let's filter the least terns data with multiple conditions. We'll get all rows for 2023 where there were at least 10 fledglings reported. We'll use the `fl_min` column for the minimum reported fledgling count. Here's the call to `.filter`:

In [52]:
terns.filter(
    (pl.col("year") == 2023) &
    (pl.col("fl_min") > 10)
)

shape: (14, 43)
┌──────┬────────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ year ┆ site_name  ┆ site_name_ ┆ site_name_ ┆ … ┆ last_obser ┆ first_nes ┆ first_chi ┆ first_fle │
│ ---  ┆ ---        ┆ 2013_2018  ┆ 1988_2001  ┆   ┆ ved        ┆ t         ┆ ck        ┆ dge       │
│ i64  ┆ str        ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ ---       │
│      ┆            ┆ str        ┆ str        ┆   ┆ str        ┆ str       ┆ str       ┆ str       │
╞══════╪════════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2023 ┆ ALAMEDA    ┆ Alameda    ┆ NA_2013_20 ┆ … ┆ 2023-09-09 ┆ 2023-06-1 ┆ 2023-07-0 ┆ null      │
│      ┆ POINT      ┆ Point      ┆ 18 POLYGON ┆   ┆            ┆ 7         ┆ 9         ┆           │
│ 2023 ┆ HAYWARD    ┆ Hayward    ┆ NA_2013_20 ┆ … ┆ 2023-09-11 ┆ 2023-05-3 ┆ 2023-06-1 ┆ null      │
│      ┆ REGIONAL   ┆ Regional   ┆ 18 POLYGON ┆   ┆            ┆ 0         ┆ 7         ┆           │
│      ┆ SHORELINE  ┆ Shoreline  ┆            ┆   ┆            ┆           ┆           ┆           │
│ 2023 ┆ OCEANO     ┆ Oceano     ┆ NA_2013_20 ┆ … ┆ 2023-08-20 ┆ 2023-06-0 ┆ 2023-06-1 ┆ null      │
│      ┆ DUNES      ┆ Dunes      ┆ 18 POLYGON ┆   ┆            ┆ 1         ┆ 9         ┆           │
│      ┆ STATE      ┆ State      ┆            ┆   ┆            ┆           ┆           ┆           │
│      ┆ VEHICULAR  ┆ Vehicular  ┆            ┆   ┆            ┆           ┆           ┆           │
│      ┆ R…         ┆ R…         ┆            ┆   ┆            ┆           ┆           ┆           │
│ 2023 ┆ VANDENBERG ┆ Vandenberg ┆ NA_2013_20 ┆ … ┆ 2023-08-26 ┆ 2023-06-0 ┆ 2023-06-2 ┆ null      │
│      ┆ SFB        ┆ AFB        ┆ 18 POLYGON ┆   ┆            ┆ 1         ┆ 5         ┆           │
│ 2023 ┆ NBVC POINT ┆ NBVC Point ┆ NA_2013_20 ┆ … ┆ 2023-09-02 ┆ 2023-05-2 ┆ 2023-06-1 ┆ null      │
│      ┆ MUGU       ┆ Mugu       ┆ 18 POLYGON ┆   ┆            ┆ 1         ┆ 4         ┆           │
│ …    ┆ …          ┆ …          ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 2023 ┆ BATIQUITOS ┆ Batiquitos ┆ NA_2013_20 ┆ … ┆ 2023-08-03 ┆ 2023-05-1 ┆ 2023-06-0 ┆ null      │
│      ┆ LAGOON     ┆ Lagoon     ┆ 18 POLYGON ┆   ┆            ┆ 1         ┆ 5         ┆           │
│      ┆ ECOLOGICAL ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│      ┆ R…         ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ 2023 ┆ SAN        ┆ San        ┆ NA_2013_20 ┆ … ┆ 2023-09-02 ┆ 2023-05-2 ┆ null      ┆ null      │
│      ┆ DIEGUITO   ┆ Diequito   ┆ 18 POLYGON ┆   ┆            ┆ 4         ┆           ┆           │
│      ┆ LAGOON ECO ┆ Lagoon     ┆            ┆   ┆            ┆           ┆           ┆           │
│      ┆ LOGICAL…   ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ 2023 ┆ MISSION    ┆ FAA Island ┆ NA_2013_20 ┆ … ┆ 2023-08-17 ┆ 2023-05-1 ┆ 2023-05-2 ┆ null      │
│      ┆ BAY FAA    ┆            ┆ 18 POLYGON ┆   ┆            ┆ 0         ┆ 8         ┆           │
│      ┆ ISLAND     ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ 2023 ┆ NAVAL      ┆ Naval Base ┆ NA_2013_20 ┆ … ┆ 2023-09-09 ┆ 2023-05-0 ┆ 2023-05-3 ┆ null      │
│      ┆ AMPHIBIOUS ┆ Coronado   ┆ 18 POLYGON ┆   ┆            ┆ 7         ┆ 1         ┆           │
│      ┆ BASE       ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│      ┆ CORONADO   ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ 2023 ┆ TIJUANA    ┆ Tijuana    ┆ NA_2013_20 ┆ … ┆ 2023-08-28 ┆ 2023-05-1 ┆ 2023-06-1 ┆ null      │
│      ┆ ESTUARY    ┆ Estuary    ┆ 18 POLYGON ┆   ┆            ┆ 2         ┆ 0         ┆           │
│      ┆ NERR       ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
└──────┴────────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

This gives us 14 sites with at least 10 fledglings in 2023. Notice that we had to put the conditions in parentheses `()` so that Python gets the order of operations right.